version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "50001:50001"
    restart: always
    # depends_on:
    #   - db
    networks:
      ci-cd:
        ipv4_address: 10.29.0.5
  db:
    image: mysql
    restart: always
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taotenladb
      MYSQL_USER: test
      MYSQL_PASSWORD: password

    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      ci-cd:
        ipv4_address: 10.29.0.6

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8088:80
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      ci-cd:
        ipv4_address: 10.29.0.7

networks:
  ci-cd:
    ipam:
      config:
        - subnet: 10.29.0.0/16